title: [Gayathri Venkateswaran]
logo: /Images/headshot.png
description:  [Gayathri is a Data Scientist at Tensor Data Scientists. She uses Data Science techniques such as machine learning, optimization, and visualization to extract maximum value from data. She has proven experience in mapping real-world business challenges with technical solutions.]
show_downloads: true
#theme: jekyll-theme-minimal
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
